version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:13.0

    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run: mvn clean test
      - run: mvn jacoco:report
      - store_test_results:
        path: target/surefire-reports
      - store_artifacts:
        path: target/site/jacoco

workflows:
  verification:
    jobs:
      - build-and-test