version: 2
jobs:
  build:
    docker:
      - image:cimg/openjdk:13
    steps:
      - checkout
      - run:
        command: mvn -B -DskipTests clean package
  test:
    docker:
      - image:cimg/openjdk:13.0
    steps:
      - checkout
      - run:
        command: mvn test
  workflows:
    build_and_test:
      jobs:
        - build
        - test:
            requires:
              - build

